core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("feedback/", views.feedback, name="feedback"),
    path("catering/", views.catering, name="catering"),
    path("login/", views.login, name="login")
]

metro_munch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("logout/", views.custom_logout, name="logout"),
    path("", include("django.contrib.auth.urls")),
]

catering/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Package(models.Model):
    created_at = models.DateTimeField(_("Date Created"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Date Updated"), auto_now=True)
    title = models.CharField(_("Title"), max_length=50)
    description = models.TextField(_("Description"))
    min_guests = models.IntegerField(_("Minimum number of guests"))
    max_guests = models.IntegerField(_("Maximum number of quests"))
    includes_appetizers = models.BooleanField(_("Includes Appetizers"), default=False)
    serving = models.BooleanField(_("Serving"), default=False)
    delivery = models.DecimalField(_("Price"), decimal_places=2, max_digits=8)

    def __str__(self):
        return self.title

core/models.py
from django.db import models
from django import forms

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"

class Feedback(models.Model):
    names = models.CharField(max_length=100, blank=False)
    email = models.EmailField(blank=False)
    message = models.CharField(max_length=255, blank=False)  
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.names} - {self.email}"

menu/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Food(models.Model):
    created_at = models.DateTimeField(_("Date Created"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Date Updated"), auto_now=True)
    name = models.CharField(_("Name"), max_length=50)
    price = models.DecimalField(_("Price"), decimal_places=2, max_digits=4)

    def __str__(self) -> str:
        return self.name


class Menu(models.Model):
    created_at = models.DateTimeField(_("Date Created"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Date Updated"), auto_now=True)
    MENU_TYPES = [
        ("B", "Breakfast"),
        ("BR", "Branch"),
        ("L", "Lunch"),
        ("S_B", "Snacks & Bev"),
        ("D", "Dinner"),
    ]
    type = models.CharField(
        _("Type of Menu"), max_length=50, choices=MENU_TYPES, default="B"
    )
    foods = models.ManyToManyField(
        "menu.Food", verbose_name=_("Foods"), related_name="menus"
    )

    def __str__(self) -> str:
        return self.type

plate/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Order(models.Model):
    created_at = models.DateTimeField(_("Date Created"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Date Updated"), auto_now=True)
    customer = models.ForeignKey("users.CustomUser", on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.customer


class OrderItem(models.Model):
    created_at = models.DateTimeField(_("Date Created"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Date Updated"), auto_now=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food = models.ForeignKey("menu.Food", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.food}-{self.quantity}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):

	def __str__(self):
		return f"{self.first_name} {self.last_name}"

core/forms.py
from django import forms
from .models import ContactMessage, Feedback

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message']

class Feedback(forms.ModelForm):
    class Meta:  
        model = Feedback
        fields = ['names', 'email', 'message']

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
)
from . import models


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = models.CustomUser
        fields = ("first_name", "last_name", "username", "email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = models.CustomUser
        fields = ("email", "password",)

core/views.py
from django.shortcuts import render, redirect
from . import forms
from django.http import HttpResponse


def index(request):
    if request.method == "POST":
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Thank you for contacting us!")
    else:
        form = forms.ContactForm()
    return render(request, "core/index.html", {"form": form})


def home(request):
    return render(request, "core/home.html")

def catering(request):
    return render(request,"core/catering.html")

def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Thank you for your feedback!")
    return render(request, 'core/feedback.html')

def catering(request):
    return render(request, "core/catering.html")

def login(request):
    return render(request,"registration/login.html")

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout
from . import forms


# Create your views here.

def signup(request):
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("core:home")
    else:
        form = forms.CustomUserCreationForm()

    return render(request, "registration/signup.html", {"form": form})


def custom_logout(request):
    logout(request)
    return redirect(reverse("core:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% include './dependancies/css.html' %}
    <title>METRO MUNCH | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include './components/header.html' %}
    {% block body %} {% endblock body %}
    {% include "./dependancies/js.html" %}
    {% include './components/footer.html' %}
  </body>
</html>

templates/components/footer.html
<footer>
	<span>&copy;Metro Munch 2023</span>
</footer>

templates/components/header.html
{% load static %}
<!-- HEADER START -->
<header>
    <!--  -->
    <nav class="navbar">
        <a href="#">
            <div class="logo">
                <img src="{% static 'img/index/logo-small.png' %}" alt="">
            </div>
        </a>
        <ul class="nav-links">
            <li>
                <a href="#">ABOUT US</a>
            </li>
            <li>
                <a href="#">SERVICES</a>
            </li>
            <li>
                <a href="#">METRO SPECIALS</a>
            </li>
            <li>
                <a href="#contact us">CONTACT US</a>
            </li>
        </ul>
    </nav>
    <!--  -->    
</header>
<!-- HEADER END -->

templates/core/catering.html
{% extends '../base.html' %}
{% load static %}


{% block title %}catering{% endblock title %}

{% block body %} 
<!--MAIN BEGIN-->
<main>

  <!--BACK-ground IMAGE BEGIN-->
  <div class="back-ground">
    <img src="{% static "img/catering/background.jpg" %}" > 

    <div>
      <h2 class="intro-text">Catering Services</h2>
   </div>
  <!--PACKAGES BEGIN-->

   <div class="packages">
    
    <!--PACKAGE-1 BEGIN-->
     <div class="package1">
       <div class="top-elements">
         <p class="package-title">Basic Package</p>
         <img class="icon" src="{% static "img/catering/basic.png" %}" alt="" />
         <p class="price">Sh. 500 Per Person</p>
       </div>
       <hr />
       <div class="bottom-elements">
         <ul class="services">
           <li>Self-service Buffet available</li>
           <li>Choose any 3 meals from our Buffet</li>
           <li>Food delivery to door-step,no set up.</li>
         </ul>
         <div class="get-button"><button>GET</button></div>
       </div>
     </div>
    <!--PACKAGE-1 END-->

    <!--PACKAGE-2 BEGIN-->
     <div class="package2">
       <div class="top-elements">
         <p class="package-title">Advanced Package</p>
         <img class="icon" src="{% static "img/catering/advanced.png" %}" alt="" />
         <p class="price">Sh. 800 Per Person</p>
       </div>
       <hr />
       <div class="bottom-elements">
         <ul class="services">
           <li>Self-service and served Buffet available</li>
           <li>Choose from any 4 meals and a drink from our menu</li>
           <li>Delivery to door-step and catering set up</li>
         </ul>
         <div class="get-button"><button>GET</button></div>
       </div>
     </div>
    <!--PACKAGE-2 END-->

    <!--PACKAGE-3 BEGIN-->
     <div class="package3">
       <div class="top-elements">
         <p class="package-title">Premium Package</p>
         <img class="icon" src="{% static "img/catering/premium-b.png" %}"alt="" />
         <p class="price">Sh. 1500 Per Person</p>
       </div>
       <hr />
       <div class="bottom-elements">
         <ul class="services">
           <li>Self-service, served Buffet and plated-sevice available</li>
           <li>Choose from any 6 meals and 2 drinks from our menu</li>
           <li>Delivery to door-step and catering set up provided</li>
           <li>Cutlery and crockery provided</li>
         </ul>
         <div class="get-button"><button>GET</button></div>
       </div>
     </div>
   </div>

   <!--PACKAGE3 END-->

   <!--PACKAGES END-->

  </div>
<!--BACK-ground IMAGE END-->

</main>
<!--MAIN END-->
{% endblock body %}

templates/core/feedback.html
{% extends '../base.html' %}
{% load static %}


{% block title %}Feedback{% endblock title %}

{% block body %}
<!-- MAIN BEGIN -->
<main class="main">
    <div class="pizza">
        <img src="{% static 'img/feedback/pizza.png' %}" alt="">
    </div>
    <div class="noodles">
        <img src="{% static 'img/feedback/ramen.png' %}" alt="">
    </div>
    <div class="cake">
        <img src="{% static 'img/feedback/cake-copy.png' %}" alt="">
    </div>
    <div class="spoons">
        <img src="{% static 'img/feedback/fork-knife-spoon-copy.png' %}" alt="">
    </div>
    <div class="inner-container">
      <h3 class="upper-text">Tell us ...</h3>
      <div class="lower-elements">
        <div class="leftside-elements">
          <p>Help us help you!</p>
          <div class="thumbs-up">
            <img src="{% static 'img/feedback/feedback-thumbs-up.png' %}" />
          </div>
        </div>
        <div class="rightside-elements"> 
          <!-- FORM BEGIN -->
                <form class="form" id="Feedback" method="post">
                  <input type="hidden" name="csrfmiddlewaretoken" value="your-csrf-token-here">
                    {% csrf_token %}
                    <div>
                        <p class="feedback-txt">Feedback type</p>
                        <input
                            type="radio"
                            id="choice1"
                            name="feedback-type"
                            required
                        >
                        <label for="choice1">In-house services</label>
                        <input
                            type="radio"
                            id="choice2"
                            name="feedback-type"
                            required
                        >
                        <label for="choice2">Catering services</label>
                    </div>
                    <div>
                        <p>Names</p>
                        <input
                            type="text"
                            id="names"
                            name="names"
                            required
                        >
                    </div>
                    <div>
                        <p>Email</p>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            required
                        >
                    </div>
                    <div>
                        <p>Message</p>
                        <input
                            type="text"
                            id="message"
                            name="message"
                            required
                            >
                          </div>
                          <div class="reset-submit-buttons">
                            <button type="reset" class="reset" >reset</button>
                            <button type="submit" class="submit">submit</button>
                          </div>
                </form>  
        </div>
      </div>
    </div>
</main>
<!-- MAIN END -->
{% endblock body %}

templates/core/home.html
{% extends "../registration/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
	{% if user.is_authenticated %}
		Hi {{ user.username }}!
		<p><a href="{% url 'users:logout' %}">Log Out</a></p>
	{% else %}
		<p>You are not logged in</p>
		<a href="{% url 'users:login' %}">Log In</a> |
		<a href="{% url 'users:signup' %}">Sign Up</a>
	{% endif %}
{% endblock content %}

templates/core/index.html
{% extends './../base.html' %}
{% load static %}

{% block title %}Welcome{% endblock title %}

{% block body %}
<!-- Start of welcome page -->
<main>
    <!-- HERO -->
    <section class="hero">
        <div class="hero-logo">
            <img src="{% static 'img/index/logo-big.png' %}" alt="">
        </div>
        <div class="hero-right">
            <div class="hero-side-img">
                <img class="egg-salad" src="{% static 'img/index/egg-salad.png' %}" alt="">
                <img class="meatballs" src="{% static 'img/index/meatballs.png' %}" alt="">
            </div>
            <div class="hero-footer">
                <div class="hero-text">
                    <span>Bringing class to cuisine</span>
                    <span>Good food,perfect service,wonderful mood</span>
                </div>
                <div class="cta">
                    <a href="{% url 'users:login' %}">LOG IN</a>
                    <a href="{% url 'users:signup' %}">SIGN UP</a>
                </div>
            </div>
        </div>
    </section>
    <!-- HERO END -->
    <!-- ABOUT US START -->
    <section id="about-us" class="about-us"></section>
    <!-- ABOUT US END -->
    <!-- SERVICES START -->
    <section id="services" class="services"></section>
    <!-- SERVICES END -->
    <!-- CONTACT US START -->
    <section id="contact-us" class="contact-us"></section>
    <!-- CONTACT US END -->
    <!-- METRO SPECIALS START -->
    <section id="metro-specials" class="metro-specials">
        <!-- METRO SPECIALS END -->
        <div class="food-day-container">
            <h2 class="food-title">Savory Sunday</h2>
            <div class="food-day-body">
                <div class="food-image">
                    <img src="{% static 'img/index/milkshake.png' %}" alt="">
                </div>
                <p class="food-text">
                    Kick off the week with a burst of sweet and savory flavors!
                            Indulge in sweet delights and pair them with creamy milkshakes. Satisfy your cravings with chocolate, strawberry, or vanilla flavors. Elevate your Sunday indulgence with our delectable treats and refreshing milkshakes.
                </p>
            </div>
        </div>
        <div class="food-day-container">
            <h2 class="food-title">Meaty Monday</h2>
            <div class="food-day-body">
                <p class="food-text">
                    Start your day with a protein-packed day! 
                            Sink your teeth into tender and juicy steak, expertly cooked to perfection. 
                            Choose from a selection of prime cuts, such as ribeye or filet mignon, bursting with flavor. Accompanied by delectable sides and sauces.
                </p>
                <div class="food-image">
                    <img src="{% static 'img/index/ribs.png' %}" alt="">
                </div>
            </div>
        </div>
        <div class="food-day-container">
            <h2 class="food-title">Taco Tuesday</h2>
            <div class="food-day-body">
                <div class="food-image">
                    <img src="{% static 'img/index/tacos.png' %}" alt="">
                </div>
                <p class="food-text">
                    Spice up your Tuesday with a fiesta of flavors! 
                            Build your own tacos with a variety of fillings like grilled shrimp, seasoned ground beef, or marinated grilled chicken. Top them off with fresh salsa, guacamole, and a sprinkle of cheese.
                </p>
            </div>
        </div>
        <div class="food-day-container">
            <h2 class="food-title">Wholesome Wednesday</h2>
            <div class="food-day-body">
                <p class="food-text">
                    Enjoy a colourful salad bursting with fresh green, vibrant
                            veggies, and grilled chicken or tofu.For a healthier option,
                            try a bowl of quinoa or a veggie stir-fry.
                </p>
                <div class="food-image">
                    <img src="{% static 'img/index/chicken-salad.png' %}" alt="">
                </div>
            </div>
        </div>
        <div class="food-day-container">
            <h2 class="food-title">Traditional Thursday</h2>
            <div class="food-day-body">
                <div class="food-image">
                    <img src="{% static 'img/index/ugali-extra.png' %}" alt="">
                </div>
                <p class="food-text">
                    Dive into flavors of Kenyan cuisines.
                            Go back to your roots with hot white or brown 
                            ugali served with a side of sukuma-wiki, wet-fried 
                            beef and kachumbari.
                </p>
            </div>
        </div>
        <div class="food-day-container">
            <h2 class="food-title">Flavour Friday</h2>
            <div class="food-day-body">
                <div class="food-image">
                    <img src="{% static 'img/index/soda.png' %}" alt="">
                </div>
                <p class="food-text">
                    Indulge in the tantalizing flavors of perfectly
                            fried fish and the satisfying crunch of golden
                            chips with a complementary 500ml soda.
                </p>
                <div class="food-image">
                    <img src="{% static 'img/index/fish-chips.png' %}" alt="">
                </div>
            </div>
        </div>
        <div class="food-day-container">
            <h2 class="food-title">Seafood Saturday</h2>
            <div class="food-day-body">
                <div class="food-image">
                    <img src="{% static 'img/index/shrimp.png' %}" alt="">
                </div>
                <p class="food-text">
                    Celebrate the end of the workweek with a 
                            seafood extravaganza! Savor succulent 
                            shrimp scampi, grilled salmon, or a seafood 
                            paella brimming with clams, mussels, and 
                            calamari. Don't forget a squeeze of lemon to 
                            enhance the flavors.
                </p>
            </div>
        </div>
    </section>
</main>
<!-- END of welcome page -->



<!-- START OF CONTACT US PAGE-->

<!-- BODY BEGIN -->
    <div class="body">
      <div class="body-form">
        <div class="spoons">
          <img class="reduce1" src="{% static 'img/feedback/fork-knife-spoon.png' %}"  />
        </div>
        <div class="ramen">
          <img class="reduce2" src="{% static 'img/feedback/ramen.png' %}" />
        </div>
        <div class="cake">
          <img class="reduce3" src="{% static 'img/feedback/cake.png' %}"  />
        </div>
        <div class="pizza">
          <img class="reduce4" src="{% static 'img/feedback/pizza.png' %}"  />
        </div>
       <div class="text1" >
         <p>Contact Us</p>
       </div>
       <div class="text2" >
         <p>
           Do you have any Questions or inquiries? Send us your queries, comments
           or complaints and we will be happy to respond to you.
         </p>
       </div>

    <!-- FORM BEGIN -->
        <form id="Feedback" class="form" method="post">
          {% csrf_token %}
          <div class="target1">
            <input 
                  class="name" 
                  type="text" 
                  placeholder="Name" />
          </div>
          <div class="target2">
            <input
              class="email"
              type="email"
              name="email"
              placeholder="email"
            />
          </div>
          <div class="target3">
            <input
              type="text"
              name="message"
              class="message"
              placeholder="Message"
            />
          </div>
          <div class="send">
            <button type="submit"  class="send1">Send</button>
          </div>
        </form>
        <!-- FORM END -->
        
      </div>
      <div class="contact-info">
        <div class="text3">
          <p>contact info</p>
        </div>
        <div class="location-icon">
          <img src="{% static 'img/contact-us/location-icon.png' %}"  />
        </div>
        <div class="text4">
          <label>River Road, Kijani.</label>
        </div>
        <div class="phone-icon">
          <img src="{% static 'img/contact-us/phone-icon.png' %}"/>
        </div>
        <div class="text5">
          <label>+873 933 920123</label>
        </div>
        <div class="instagram-icon">
          <img src="{% static 'img/contact-us/instagram-icon.png' %}" />
        </div>
        <div class="text6">
          <label> @metro_munch873</label>
        </div>
        
        <div class="email-icon">
          <img src="{% static 'img/contact-us/email-icon.png' %}" alt="" />
        </div>
        <div class="text7">
          <label>metromunch@gmail.com</label>
        </div>
        <div class="clock-icon">
          <img src="{% static 'img/contact-us/clock-icon.png' %}" />
        </div>
        <div class="text8">
          <label>Open 24hrs</label>
        </div>
        </div>
      </div>
    </div>
<!-- BODY END -->
{% endblock %}

templates/dependancies/css.html
{% load static %}

<!--
	<link rel="stylesheet" href="{% static 'css/<folder-name>/<file-name.css>' %}" />
-->

<link rel="stylesheet" href="{% static 'css/core/index.css' %}" />
<link rel="stylesheet" href="{% static 'css/core/feedback.css' %}" />
<link rel="stylesheet" href="{% static 'css/core/catering.css' %}" />
<link rel="stylesheet" href="{% static 'css/core/contact-us.css' %}" />
<link rel="stylesheet" href="{% static 'css/components/header.css' %}" />
<link rel="stylesheet" href="{% static 'css/components/footer.css' %}" />
<link rel="stylesheet" href="{% static 'css/registration/login.css' %}" />

templates/dependancies/js.html
{% load static %}

<script src="{% static 'js/carousel.js' %}"></script>